#:kivy 1.0.9

<ObstacleWrapper>:
    # Playground size is 690, 590
    #   Start at position 5, 5 to 695, 595
    # Coordination system bottom-left (5, 5) - top-right (695, 595)


    Obstacle:
        pos: 5, 445
        size: 250, 1

    Obstacle:
        pos: 255, 445
        size: 1, 150
    
    Obstacle:
        pos: 55, 545
        size: 50, 1

    Obstacle:
        pos: 105, 445
        size: 1, 50

    Obstacle:
        pos: 155, 495
        size: 1, 50

    Obstacle:
        pos: 155, 495
        size: 50, 1

    Obstacle:
        pos: 205, 495
        size: 1, 50

<ObjectiveWrapper>:
    # Playground size is 690, 590
    #   Start at position 5, 5 to 695, 595
    # Coordination system bottom-left (5, 5) - top-right (695, 595)

    # Objective:
    #     pos: 500, 50
    #     size: 20, 20

